### ISSUE TITLE
Why You are checking DIR_IP in run.sh

### ISSUE THREAD

**Issue by vrx-666** [martmaiste/bacula-fd#2]
I don't understand why You are doing this?
`if [ -z "${DIR_IP}" ]; then
	echo "==> Adding DIR_IP to /etc/hosts"
	echo "${DIR_IP} ${DIR_NAME}" >> /etc/hosts
fi`

It always be false because You are set DIR_IP earlier in the script.
So DIR_IP and DIR_NAME never go to hosts file

**Comment by martmaiste** [comment]
Probably to allow overriding DIR_IP using ENV at docker run. At the beginning of the scripts are my defaults.

**Comment by vrx-666** [comment]
Yeah, but -z condition mean that DIR_IP is zero length ( is empty ).
So if DIR_IP is empty then echo dir_ip dir_name to etc/hosts ?
Do You know what I mean?
You should use -n or 
`! -z`

**Comment by martmaiste** [comment]
You are correct. I'm pretty sure that this option did not find any use but it's now fixed anyway. Thanks!
